apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatapp-backend
  template:
    metadata:
      labels:
        app: ai-chatapp-backend
    spec:
      containers:
        - name: backend
          image: ikhyati/ai-chatapp-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: ai-chatapp-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
